# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'passthepiece' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for passthepiece
  pod 'Cards'
  pod 'HidingNavigationBar', '~> 2.0'
  pod "Atributika"
  pod 'AlamofireImage', '~> 3.3'
  pod 'Alamofire', '~> 4.5'
  
  target 'passthepieceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'passthepieceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
